sentence = input("Enter a sentence: ")
print("Uppercase:", sentence.upper())
print("Lowercase:", sentence.lower())
search_word = input("Enter a word to search: ")
position = sentence.find(search_word)
print(search_word,"was found at position", position)
old_word = input("Enter the word to replace: ")
new_word = input("Enter the new word: ")
replaced_sentence = sentence.replace(old_word, new_word)
print("Updated sentence:", replaced_sentence)
words = sentence.split()
print("Words in the sentence:", words)  
print("Total number of characters:", len(sentence))